grafana:
  fullnameOverride: grafana
  grafana.ini:
    server:
      root_url: https://grafana.labtime.work/
    feature_toggles:
      provisioning: true
    provisioning:
      repository_types: "git|github|gitlab"
  admin:
    existingSecret: grafana-secret
    userKey: ADMIN_USER
    passwordKey: ADMIN_PASSWORD
  envFromSecret: grafana-secret
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Financedash
          uid: financedash-postgresql
          type: postgres
          url: azana-postgresql.azana:5432
          user: financedash
          secureJsonData:
            password: ${POSTGRES_PASSWORD}
          jsonData:
            database: financedash
            sslmode: disable
            postgresVersion: 1500
            timescaledb: false