grafana:
  fullnameOverride: grafana
  grafana.ini:
    server:
      root_url: https://grafana.labtime.work/
    feature_toggles:
      provisioning: true
    provisioning:
      repository_types: "git|github|gitlab"
  admin:
    existingSecret: grafana-secret
    userKey: ADMIN_USER
    passwordKey: ADMIN_PASSWORD
  envFromSecret: grafana-secret
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Financedash
          uid: financedash-postgresql
          type: postgres
          url: azana-postgresql.azana:5432
          user: financedash
          secureJsonData:
            password: ${POSTGRES_PASSWORD}
          jsonData:
            database: financedash
            sslmode: disable
            postgresVersion: 1500
            timescaledb: false
        - name: Tempo
          uid: tempo
          type: tempo
          url: http://tempo:3100
          access: proxy
          isDefault: false
          jsonData:
            httpMethod: GET
            nodeGraph:
              enabled: true
            search:
              hide: false

tempo:
  fullnameOverride: tempo
  tempo:
    retention: 336h  # 14 days
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
  persistence:
    enabled: true
    size: 10Gi
  service:
    type: ClusterIP