apiVersion: v2
name: gitlab-runner
description: A Helm chart for configuring gitlab-runner
type: application
version: 0.81.0

dependencies:
  - name: gitlab-runner 
    version: 0.81.0
    repository: https://charts.gitlab.io/
