version: 2
updates:
  - directory: "/kubernetes"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
    package-ecosystem: "helm"
    schedule:
      interval: "weekly"
