---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBNwbvVy/L84Tfe54jSYqfPwzx/ab/9TdVq7IY2MZ+SKA2nylHrRVxD/SbqdMuH3gqgczGmAxvYSx8vhb10wUWYU7E9/dhGXSuTXP2QBkAE2ESBwK0YnC1BNqramWTAsEiReNPRhE+C/0p1ZiGRqddEkAESQ3YUA09a8Jf05RBoPU1Ct9FOnNn+VJEyfWwjPsgXtXoMxQf07ErhnHv/VarDTLm/kR32oPAHmLIO/BIZVM1rP5sSUPf57gn8zmYzVw+5PXuGn5x3Tfm7uZ0aqTRgEqNjnsoxRzxn9UKwMgVGBNqZ00LEbpEpJpDBSHB++4sHr5qvg8pE40Ur2xLJxUxqGPuasc6xOAVJRu40KKfjl66ctFKW1nF8l9FDXC7XoMrgZS/x/Wdj5kHWNewgM5qQzaxcjVm3SF1nsL4XdrQdP50UO62qXz/Q+qXyrimcqHvo14+yFtPNCNv3q5kwW0mINjYjyCgUVd4/a7FF5CxpvgjHpq3EkcCGKbU+vTywzwrYUXLdHgfabWkor3TcpjLWDUVlASThu0/PRRCBR9PDaPx2h9B+bEr2MoC97mfjkoCeMJI8HVxXOWMAOPKDARpaEPGGeEeK8hisSW+Hc1hqDm6MXpvABH0dflxeY+sXHxX4Tsa275tKUrj0JSVo+lKbNmcBA+aAClqlMf8OznpeiRsWljVE5SInvgX3hFJX5PMWfzKBp0M6CSYMlipoFgUTvDFcg+NY7YTYGp9EJmVhdllEW1Ovn1R4b9uBuEAgAFR4CwhMkvidA4CChNuE15j8xQOeVTqsVzrkG10uoCn+XuLnJpBJBw3vctrr/SiNKTW7uxK8GxIGLepWfBelCz+SR64BCsOSKHzAQNBsNuz7G5Vdw4X8AbCB1WR0nubPC9efszX3LTAwZQI8Au2vT56qCga0ySnG0aN+voCXBI6+nV4nDpWeZy1T
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
    type: Opaque
