---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAUrd9VthlPXuDo7uD0+nZG32VNF30dDMy4oEXH7xBwazwDhYQVnwD/x6p87UK74MUlMH9PeEx+N7HKA2zJCHZ3gzFFoUtesWo3Uk2Y4jrfImfwIe1Yt9+Ffr5fPwg6KvpWHLRMLL4kWOI16U2XDmP0SZ8vc76PuaxrKuPnacsnf7+oNLovY56iPF18Ju+odqyevEf7ktPR3mno/T2JiBjzdoGmEaEvjgG46pNlKziTN5TkoVIG0GacQJSgWR2tOzlTdo6AvA6elaC2rX8LnU96bflN/ZAfSPDqfgaaBPBbFEgBwZjmcrmLKYz3JnyjyRTrfoInyu1WmXblmk62MTSU08YZUk8YYN9O7604CmPEqht3hdFO9taNvGt6SmWrIHwIVUMdNuPxIcFAjsE9ysF0Z91jV6G7WA/pBapoMmiIKN9GXXgjUoWs73d3RgUOGOUMXDhzLkPiRRxQU/dxuo8OeBGBj60EynB9XbjaOxQcyweMLGno4PfgXBC82y77iPn8DLfCdQbWBkn6THPl2QlKQhSwxDGGgBJICv4VHcqmKU/vJ6ICOwe0y8dSa+DbYXcj1DDwKJqgEvA7bPRPEU76+XFrh2dYkGi+exnXfsZLFx2xqb1gZzr/f6iEWflKRp4KAyC66xbtQu9eh0Wryt5UGWzmOTCozJekqFSlbYE6iPza7CAcC0UVjv1aQBLZEdmW6fTDAurG5SgGdQB/N/80dihz63OnLwzwLJBLTxORs1dg0oI8eS9Psx3TInP9FM+ckSFUx/dZpBGnYyYxX5UOhMundEVwd2O2hxgQcA9Z5XriD4F9ErTHadiDp2C95tIpfBrkAHahu4y/yhEzKqJmglViecGweq0XdYicTmpkCB8wgQZ5Cj3XkBB/SxONVGswk0etxcsDh5OThDKVPZpcJv+DSqz/PKpPV43p17US2OFmxJHHkSm3vrYzALitCSqta1/5iUdQRelvxCTd+hIMRJs/xaaCyRSFP3oKr0a4CMoyljIWlVJGaz4d3l4Qvlg=
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
    type: Opaque
