---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBqBee8nE+MpJKxdAXSUC7H5ay0KC6eXAKCjHgE9d52RjgCQZzV7ru1GVkHvnGLWM9bBjGTuBoZz/W2MKIm98Hl4r0eYtj+SI7sYpgAqMPlX4K1JaZPDWc7otbe49ZeyOJpvu6sDqYjJljpxcnfR5l/1WAN73SWrAo0fWBNGQxK0B7AJL9XNfhy++90aEMqqasVX0a4WKTuAfk4PasGRZ7gJN7KufPMhOgVX/TtuR7sW3zWcXQXedOfwFbaaxqucegP6b/tjrrSX5nnsOOb4hJcuxb5Rax2BGWECWzgVkae/o3jOwsi3ti+amq04UBg3VK0cySsfb7lsgWIFWJntqkY2fXuV4V4xk/V12Scf0Ef+sU/YMB3RZjANOjHRYQEskQrr+TWze++hM16APMGwTsCuEdf+J0rwfzyValA0A6B81H3gZxdj9EfCS3IT6ZImAm4Qg83wlG3KAvSBysdYqGwCFovylwvAHZ5tbzVC/vlMQajasofC0mGyv/SOPOaWLEzuR3jt4LCaqhWVRmIlXyabO4nAtLtXlg832xgxXKQt2d09Ab7DpYSLVOHu7ss+nirX33IoLF2/1KUdDHqPYgTQWV+JPSjM4wWQrjCpU3xeNHfBqRbCP1Eoi7srBz1qB6TISu0xXQUF9ig0gD7tXnYQxuzpteyI3QcRRGT8vLzzdrJ1tw1+vYuEwWysG5XDzxgi3rm1Mio5/wrPEXLfnwaDsgj4TrMDAwWmtEFvA==
    admin-user: AgBJImoKVQV+YZw7fJOI0mrVh8RHZJp9x80N44iwb3nXUz0bgfftSjayLFlRu1D/L7oOGo8I+hFT3bl6/kRqslq2uvZB1vWw96CGiBk+WEhZkdUa4PRAPzN0sh3RF+ZycwCdFsi421J4NHKzGIHJelz503hlwHHZlDP8LIoB8E5NX1EW9vjAuJuah2ilvUvSUD9fmVO7Z8zM/XPdpBknPO4Ao0wFQ0iFjiUxAon8VJDKRDN3UoUvOPgyPkEhtdEGCW05yZmKMYbWClkgQOG3AflUlaIW3XpjshM1ir8RFSxsTqunG0hYP092YKX8hJBx+5OXlkyxvG4U7qBt+Hla1TlRzrRzfhWolAHA5VEe3Y4kZ0TezuCdwZExn4irZ69ReuqGGU6yxhgJbZPMkzsvhcDGHxybrboGU5Go7DxxV4TrG5IyPbfDpar0B687OMGAuSdXX1spTlyVa6dgh2EOpe5OTw/c72w1XZY6bh0RxPQV7TxCCU9ygJh8HTlgIcrg6e8jvgdNPq4dcZRo5pDaC0ym4Sz9lj7VC+1uoldDv7v+bmQWDeHhtKoLJCbHdYyWxzQ8u/ruBYhwl5vrWaHT90aaYcSWCzQdPAxUEKhCvglODx46jbDFut2YyC8s1d6aFt4a9u+bazDFRZEvMJqixc9LZTZPgaMSGMrHfJ4ri4CLUE7s8NnUHjW6n6Y3gF9X3Co8T3JKWA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
