argocd-apps:
  cluster: prod-gke-01
  apps:
    - name: azana
      path: backend/k8s
      repoUrl: https://gitlab.com/azana1/flego.git
      cluster: arziqi-prod-gke-01
      namespace: azana
      helmValueFiles:
        - values.yaml
        - current-tag.yaml
    - name: cloudflared
      path: kubernetes/apps/cloudflared
      cluster: arziqi-prod-gke-01
      namespace: cloudflared
      kustomizeEnabled: true
    - name: sealed-secrets
      path: kubernetes/apps/sealed-secrets
      cluster: arziqi-prod-gke-01
      namespace: sealed-secrets
    - name: monitoring
      path: kubernetes/apps/monitoring
      cluster: arziqi-prod-gke-01
      namespace: monitoring
  namespaces: []
