argocd-apps:
  cluster: arziqi-prod-gke-01
  apps:
    - name: azana
      path: backend/k8s
      repoUrl: https://gitlab.com/azana1/flego.git
      namespace: azana
      helmValueFiles:
        - values.yaml
        - current-tag.yaml
    - name: cloudflared
      path: kubernetes/apps/cloudflared
      namespace: cloudflared
      kustomizeEnabled: true
    - name: sealed-secrets
      path: kubernetes/apps/sealed-secrets
      namespace: sealed-secrets
    # Disabled for now; uncomment to bring Grafana back.
    # - name: monitoring
    #   path: kubernetes/apps/monitoring
    #   namespace: monitoring
  namespaces: []
